# Generated by Django 4.1.4 on 2023-03-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0004_coupon_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.CharField(default='Sample', max_length=200, null=True),
        ),
    ]
